### PR TITLE
Grecaptcha not defined patch

### PR DESCRIPTION
**Pull request by arslanmurtaza**
Why and what is being done.
Grecaptcha not defined error was being raised occasionally so, added window.grecaptcha check to execute recaptcha ready method only if grecaptcha is present.
## Pre-Merge Checklist
- [ ] CHANGELOG.md updated with short summary

### CODE REVIEW

**Comment by grosser** [comment]
why do you think it is not defined ?
... this will still not make recaptcha work, are you ok with that ?

**Comment by arslanmurtaza** [comment]
@grosser I believe it is not defined due to network latency.
The recaptcha endpoint might take too much time to load, or if it might not load for some reason.

In such cases grecaptcha isn't defined.

**Comment by grosser** [comment]
if it's not defined it won't work and give no indication on why it did not work, so how is this better ? / what is the problem with it currently showing an error (end users won't see it afaik) ?

**Comment by arslanmurtaza** [comment]
Got your point, can you please let me know how can we make sure that grecaptcha is always loaded first before calling grecaptcha.ready?
We have rollbar setup on our project, and it raises error there occasionally.

**Comment by grosser** [comment]
check for defined in a loop ?
... might be some bots triggering it, so not sure how it happens

**Pull request closed without merging**
