### PR TITLE
Validate model object first, helpful when you use xhr/ajax req

### PR DESCRIPTION
**Pull request by frontandstart**
I use xhr request to send and validate data, validate model object first - prevent handling errors when you already validate captcha request but not pass own validation errors

### CODE REVIEW

**Comment by grosser** [comment]
this is a reallly bad idea ... this would mean all users can bypass recaptcha and get signed up, also would be confusing if a user gets the captcha wrong and then sees a "email already taken" validation

**Comment by grosser** [comment]
if you need it that can use something like `if user.valid? && recaptcha && user.save!(validate: false)`

**Comment by frontandstart** [comment]
@grosser Yes you are right, sorry for wasting time. Should use more clear way to do this
like you text: if validate_model && validate_recap &&

**Comment by grosser** [comment]
np, good to also have examples/discussions about what not to do around :)

**Pull request closed without merging**
