### PR TITLE
adding callback functionality

### PR DESCRIPTION
**Pull request by davingee**
1. adding callback functionality via -> https://developers.google.com/recaptcha/docs/display#render_param

### CODE REVIEW

**Comment by grosser** [comment]
- would it make sense to support all `data-*` attributes ?
 - can you add a test ?

**Comment by grosser** [comment]
uhm ... you can already pass :callback as an option ... does that not work / how is this different ?

**Comment by davingee** [comment]
<%= recaptcha_tags 'callback' => "captchaCallback" %>
and 
      <%= recaptcha_tags 'data-callback' => "captchaCallback" %>
does not currently work

**Comment by grosser** [comment]
it's a symbol, so should be`callback: 'captchaCallback'`

**Comment by davingee** [comment]
Hey Grosser,
I tried assigning callback with a symbol as well, this did not work for me.

What is the command to run the tests??
I will fix the tests

Thanks

**Comment by davingee** [comment]
HA! ok it works  sorry for the pull request, cheers

**Comment by tsaomichael** [comment]
Hey, my code  

<%= recaptcha_tags(callback: 'callback_recaptcha', theme: 'dark', timeout: 2)  %>

    jQuery(function(){
      function callback_recaptcha(){
        $('#login-btn').prop("disabled", false); 
      }


But browser console  show me ReCAPTCHA couldn't find user-provided function: callback_recaptcha

Please, how to fix ?

**Pull request closed without merging**
