### PR TITLE
Size option in v2

### PR DESCRIPTION
**Pull request by guapolo**
added size option according to API.

### CODE REVIEW

**Comment by michelgrootjans** [comment]
Can this please be merged, I need this too

**Comment by bricesanchez** [comment]
:+1: really useful, thanks @guapolo !

**Comment by diazruy** [comment]
Any chance this will be merged soon?

**Comment by kintner** [comment]
@ambethia ok to merge?

**Comment by alebruck** [comment]
:+1:

**Comment by arg** [comment]
:+1:

**Comment by grosser** [comment]
I took over the project, can you rebase + add a test + document in the readme ?

**Comment by grosser** [comment]
manually merged and added a test + readme ... please make a follow up PR with a link to where the size option is documented

**Comment by bricesanchez** [comment]
@grosser thanks !

**Pull request closed without merging**
