### PR TITLE
Remove unnecessary Timeout from v2 branch

### PR DESCRIPTION
**Pull request by olivierlacan**
Please see the reasoning here: http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/

`Net::HTTP` can handle your timeouts for you. I haven't fixed the v1 branch because I don't really need it and I'm not familiar with how to use `Net::HTTP`'s timeout facilities with the `post_form` method.

There's a good chance the test will still pass because Net::HTTP apparently also raises `Timeout::Error`

This happens to solve the issue I ran into here as well: #127

### CODE REVIEW

**Comment by olivierlacan** [comment]
@ambethia Any chance you could look at this? I've tested this a ton and deployed it to production and it works well so far.

**Comment by grosser** [comment]
can you rebase this ?

atm the timeout tests are broken, could you make them run so I can merge this with less risk ?

**Comment by olivierlacan** [comment]
Sure.

**Comment by grosser** [comment]
manually merged

**Comment by olivierlacan** [comment]
:+1:

**Pull request closed without merging**
