### PR TITLE
Support for specifying custom response param

### PR DESCRIPTION
**Pull request by makkrnic**
In cases when `recaptcha_tags` are not used, or at least not directly, it would bi nice to have option to set the response manually.

### CODE REVIEW

**Comment by grosser** [comment]
:+1:

**Comment by grosser** [comment]
I'll release this propably Monday with 1.0.0 unless there are any complaints coming.

**Comment by grosser** [comment]
1.0.0 out now in a gem store near you ;)

**Comment by makkrnic** [comment]
Great. Thank you. :D

**Pull request merged**
