### PR TITLE
tests for environment variable set in rack-based apps

### PR DESCRIPTION
**Pull request by fivepapertigers**

### CODE REVIEW

**Comment by grosser** [comment]
I'd say put it before Rails detection ... also not sure why but all tests break ... I think travis might have RACK_ENV set ... so unset it in test_helper I guess

**Comment by fivepapertigers** [comment]
Ok, should be good now. Got the tests to pass, looks like travis does set RACK_ENV.

**Comment by grosser** [comment]
thx, 1.1.0 is out!

**Comment by fivepapertigers** [comment]
Thanks for taking care of it quickly! Much appreciated.

**Pull request merged**
