### PR TITLE
Allow random attributes to be rendered for invisible captcha button

### LINKED ISSUE #222: Use Rails button_tag helper for invisible captcha
Just wondering if there's a reason to not use button_tag helper for invisible recaptcha? I'm asking because I need to set more attributes on the generated button tag (e.g. disabled and other data-X attributes). With the way it's setup now, you can only specify class it seems.

### PR DESCRIPTION
**Pull request by ngan**
Fixes #222

### CODE REVIEW

**Comment by grosser** [comment]
hmm this escalated :D 
how about `html: {foo: bar}` so we don't have to do delete ?

**Comment by ngan** [comment]
Won't that change method signatures, resulting in breaking changes?

**Comment by ngan** [comment]
If that's ok, then I have even more improvements to make.

**Comment by grosser** [comment]
hmmm ... this is all mixed up atm :/

**Comment by grosser** [comment]
yeah ... I think what you did here is pretty good ... users will see that an option was ignored when it ends up in the tag ... 
we might have to later change this if we want an option that is also a html attribute ... but at least we don't need to break anyones code just yet ...

**Comment by grosser** [comment]
4.3.0

**Pull request merged**
