### PR TITLE
Unfreeze SKIP_VERIFY_ENV array

### PR DESCRIPTION
**Pull request by gkopylov**
Currently there is an error ```can't modify frozen Array``` when you try to delete ```test``` from ```SKIP_VERIFY_ENV``` array( ```Recaptcha.configuration.skip_verify_env.delete('test')``` ) while testing.

### CODE REVIEW

**Comment by grosser** [comment]
let's make it a class variable then, constants should be erm constant ;)

**Comment by gkopylov** [comment]
@grosser may be it would be better to just delete this constant and set this array explicitly here https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/configuration.rb#L34 ?

**Comment by grosser** [comment]
that works too!

**Comment by gkopylov** [comment]
@grosser can you merge it?

**Comment by grosser** [comment]
thx, released as 3.2.0

**Pull request merged**
